CREATE TABLE [User]
(
userId INT PRIMARY KEY IDENTITY(1,1),
userName NVARCHAR(100) NOT NULL,
emailAddress NVARCHAR(255) NOT NULL UNIQUE,
contactNumber NVARCHAR(20) NOT NULL,
passwordHash NVARCHAR(255) NOT NULL,
createdDate DATETIME DEFAULT GETDATE()
);


CREATE TABLE EventOrganiser (
    organiserID INT PRIMARY KEY,
    userID INT NOT NULL UNIQUE,
    FOREIGN KEY (userID) REFERENCES [User](userId) ON DELETE CASCADE
);


CREATE TABLE Participant (
participantID INT PRIMARY KEY,
userID INT NOT NULL UNIQUE,
FOREIGN KEY (userID) REFERENCES [User](userId) ON DELETE CASCADE
);