CREATE TABLE [User]
(
userId INT PRIMARY KEY IDENTITY(1,1),
userName NVARCHAR(100) NOT NULL,
emailAddress NVARCHAR(255) NOT NULL UNIQUE,
contactNumber NVARCHAR(20) NOT NULL,
passwordHash NVARCHAR(255) NOT NULL,
createdDate DATETIME DEFAULT GETDATE()
);